/* =========================================================
   VizionIQ demo · shared data. One corridor story; every screen reads from here
   so times, places and numbers agree. Demo moment: Tue 16 Sep 2026, 08:45 AM.
   Distance markers run Km 0 (Hyderabad) to Km 570 (Bengaluru). SB = towards Bengaluru.
   ========================================================= */
VQ.data = (() => {
  const D = { now: '08:45 AM', nowSec: '08:45:12 AM', date: '16 Sep 2026', day: 'Tue, 16 Sep 2026', corridor: 'NH-44', from: 'Hyderabad', to: 'Bengaluru', km: 570 };

  D.places = [
    { name: 'Hyderabad', km: 0, major: 1 }, { name: 'Shamshabad', km: 14, minor: 1, below: 1 }, { name: 'Shadnagar', km: 48, below: 1 }, { name: 'Jadcherla', km: 85 },
    { name: 'Kothakota', km: 128, below: 1, minor: 1 }, { name: 'Pebbair', km: 152, minor: 1 }, { name: 'Kurnool', km: 212, major: 1, below: 1 }, { name: 'Dhone', km: 265, minor: 1 },
    { name: 'Gooty', km: 305, below: 1 }, { name: 'Anantapur', km: 360, major: 1 }, { name: 'Penukonda', km: 430, below: 1 }, { name: 'Bagepalli', km: 470, minor: 1 },
    { name: 'Chikkaballapur', km: 510 }, { name: 'Devanahalli', km: 535, minor: 1 }, { name: 'Bengaluru', km: 570, major: 1 },
  ];
  D.nearest = km => D.places.reduce((a, b) => Math.abs(b.km - km) < Math.abs(a.km - km) ? b : a).name;
  D.kmLabel = km => `Km ${Number.isInteger(km) ? km : km.toFixed(1)}`;

  D.sections = [
    { name: 'Hyderabad – Jadcherla', from: 0, to: 85, normal: 65, current: 96 },
    { name: 'Jadcherla – Kurnool', from: 85, to: 212, normal: 95, current: 102 },
    { name: 'Kurnool – Anantapur', from: 212, to: 360, normal: 110, current: 126 },
    { name: 'Anantapur – Bengaluru', from: 360, to: 570, normal: 160, current: 178 },
  ]; /* minutes. totals: normal 430 (7 h 10 m), current 502 (8 h 22 m), +72 min = +17%.
     Added time by section matches its causes: +31 (accident 22, Raikal toll queue 9), +7 (stalled truck 5, other 2), +16 (roadworks 8, stranded HGV 8), +18 (waterlogging 14, rain and fog 4) */
  D.hm = m => `${Math.floor(m / 60)} h ${String(m % 60).padStart(2, '0')} m`;

  D.speedSegments = [
    { from: 0, to: 14, state: 'moderate', speed: 64, note: 'City edge, moderate' }, { from: 14, to: 52, state: 'free', speed: 92 },
    { from: 52, to: 58, state: 'slow', speed: 42, note: 'Raikal toll plaza queue' }, { from: 58, to: 79.7, state: 'free', speed: 88 },
    { from: 79.7, to: 84.5, state: 'congested', speed: 12, note: 'Queue behind accident at Km 84.5' }, { from: 84.5, to: 90, state: 'moderate', speed: 62, note: 'Recovering after accident site' },
    { from: 90, to: 126, state: 'free', speed: 94 }, { from: 126, to: 131.2, state: 'slow', speed: 46, note: 'Stalled truck at Km 131.2' }, { from: 131.2, to: 170, state: 'free', speed: 91 },
    { from: 170, to: 177, state: 'moderate', speed: 68, note: 'Debris at Km 176.3' }, { from: 177, to: 262, state: 'free', speed: 93 }, { from: 262, to: 270, state: 'slow', speed: 44, note: 'Roadworks lane closure' },
    { from: 270, to: 292, state: 'free', speed: 86 }, { from: 292, to: 297, state: 'slow', speed: 41, note: 'Stranded heavy vehicle on gradient' }, { from: 297, to: 318, state: 'free', speed: 84 },
    { from: 318, to: 323, state: 'moderate', speed: 66, note: 'Cattle on carriageway' }, { from: 323, to: 392, state: 'free', speed: 95 }, { from: 392, to: 399, state: 'moderate', speed: 63, note: 'Vehicle smoke alert at Km 398' },
    { from: 399, to: 425, state: 'free', speed: 90 }, { from: 425, to: 436, state: 'moderate', speed: 61, note: 'Heavy rain' }, { from: 436, to: 442, state: 'slow', speed: 28, note: 'Waterlogging at Km 441' },
    { from: 442, to: 470, state: 'moderate', speed: 64, note: 'Heavy rain' }, { from: 470, to: 530, state: 'free', speed: 89 }, { from: 530, to: 548, state: 'moderate', speed: 62, note: 'Low visibility, easing' },
    { from: 548, to: 562, state: 'free', speed: 85 }, { from: 562, to: 570, state: 'moderate', speed: 58, note: 'Bengaluru entry' },
  ];

  D.home = { activeIncidents: 12, incidentsDelta: 3, vehiclesHour: 72540, vehiclesDelta: 6, travelNow: 502, travelNormal: 430, tollToday: 1.28, tollDelta: 4, assetAlerts: 5, assetNew: 2, avgSpeed: 68, avgSpeedDelta: -12, diversions: 2 };

  /* incident types */
  D.types = {
    accident: { label: 'Accident', icon: 'alert', tone: 'crit' }, stalled: { label: 'Stalled Vehicle', icon: 'car', tone: 'crit' }, wrongway: { label: 'Wrong-Way Vehicle', icon: 'ban', tone: 'crit' },
    flooding: { label: 'Weather / Flooding', icon: 'rain', tone: 'violet' }, debris: { label: 'Obstacle / Debris', icon: 'octagon', tone: 'warn' }, roadworks: { label: 'Roadwork', icon: 'cone', tone: 'serious' },
    animal: { label: 'Animal', icon: 'paw', tone: 'info' }, pedestrian: { label: 'Pedestrian', icon: 'walk', tone: 'good' }, smoke: { label: 'Vehicle Fire / Smoke', icon: 'flame', tone: 'crit' },
    queue: { label: 'Slow Traffic', icon: 'cone', tone: 'warn' }, hgv: { label: 'Stranded Heavy Vehicle', icon: 'truck', tone: 'serious' }, visibility: { label: 'Low Visibility', icon: 'fog', tone: 'violet' },
  };
  D.last24h = { total: 48, byType: [['accident', 14], ['stalled', 10], ['roadworks', 7], ['debris', 5], ['flooding', 4], ['animal', 3], ['pedestrian', 2], ['other', 3]], bySev: [['High', 14, 'crit'], ['Medium', 21, 'warn'], ['Low', 10, 'good'], ['Info', 3, 'gray']] };
  D.response = { underResponse: 5, resolvedToday: 6, avgResponseMin: 8, avgResponseDelta: -35, detectToAlertSec: 42, clearanceMin: 47 };

  D.hotspots = [
    { id: 'HS-01', name: 'Jadcherla junction merge', from: 82, to: 86, kind: 'Accident hotspot', count90: 9, pattern: 'Rear-end and side-swipe collisions where the Mahbubnagar link merges; 7 of 9 between 07:30 and 09:30', fix: 'Extend merge taper by 120 m, add advance VMS warning and rumble strips' },
    { id: 'HS-02', name: 'Gooty ghat gradient', from: 294, to: 298, kind: 'Breakdown hotspot', count90: 11, pattern: 'Loaded multi-axle trucks overheating on the 4.2% climb; clusters on days above 34°C', fix: 'Add a crawler lane lay-by at Km 295 and station a recovery crane at Gooty' },
    { id: 'HS-03', name: 'Penukonda underpass approach', from: 438, to: 442, kind: 'Waterlogging hotspot', count90: 6, pattern: 'Water collects within 30 minutes once rainfall passes 25 mm/h; side drain blocked twice this season', fix: 'Desilt the side drain, add a pump sump and a water-level sensor' },
    { id: 'HS-04', name: 'Shamshabad ORR service link', from: 8, to: 11, kind: 'Wrong-way entry hotspot', count90: 5, pattern: 'Two-wheelers and light vehicles cut back along the exit ramp to avoid a 6 km U-turn', fix: 'Install tyre-killer strip and wrong-way signage on the ramp; open the median U-turn at Km 12' },
    { id: 'HS-05', name: 'Gooty grazing belt', from: 318, to: 324, kind: 'Animal intrusion hotspot', count90: 8, pattern: 'Cattle cross between 06:30 and 08:00 where the median fence is broken', fix: 'Repair 340 m of median fence and add a cattle underpass sign set' },
  ];

  /* ---------- live incidents ---------- */
  const A = (icon, title, sub, btn, primary, tone) => ({ icon, title, sub, btn, primary, tone });
  D.incidents = [
    { id: 'INC-2040', type: 'accident', title: 'Accident / Collision', sev: 'high', km: 84.5, dir: 'SB', near: 'Near Jadcherla', lane: '2 of 3 lanes (Lane 1 &amp; 2)', at: '08:32 AM', mins: 13, status: 'Response in progress',
      line1: '2 lanes blocked', line2: 'Multiple vehicles involved', banner: ['Multiple vehicles', '2 lanes blocked'], img: 'cam-accident.jpg', baked: 1, camId: 'NH-44_Km84_5_SB', hotspot: 'HS-01', weather: 'Clear · 28°C · Good visibility',
      boxes: [{ x: 4, y: 33, w: 26, h: 40, label: 'Truck', tone: 'crit' }, { x: 30, y: 48, w: 20, h: 26, label: 'Car 1', tone: 'crit' }, { x: 49, y: 54, w: 31, h: 26, label: 'Car 2', tone: 'crit' }],
      vehicles: [{ name: 'Heavy Truck', kind: 'Commercial vehicle', lane: 'Lane 1', damage: 'Major Damage', tone: 'crit' }, { name: 'Car 1 (SUV)', kind: 'Private vehicle', lane: 'Lane 2', damage: 'Major Damage', tone: 'crit' }, { name: 'Car 2 (Sedan)', kind: 'Private vehicle', lane: 'Lane 2', damage: 'Moderate Damage', tone: 'warn' }],
      intelTitle: 'Collision intelligence', intel: [['car', 'Vehicles involved', '3 (1 truck, 2 cars)'], ['road', 'Lanes affected', '2 of 3 (Lane 1 &amp; 2)'], ['alert', 'Severity indicators', 'Airbag deployment likely, debris field 18 m'], ['trend', 'Congestion propagation', 'Queue 4.8 km, growing about 80 m a minute'], ['users', 'Nearest responder', 'Highway patrol, 4 mins (2.1 km)'], ['shield', 'Secondary collision risk', 'High at queue tail, Km 79.7']],
      ai: { detection: 'Sudden stop of 3 vehicles, then no movement for 13 minutes.', classification: 'Multi-vehicle collision (1 truck, 2 cars)', laneImpact: 'Lanes 1 and 2 blocked, Lane 3 open', trafficImpact: 'Speed down 85%, queue 4.8 km and growing', predictive: 'If not cleared by 09:30, the queue passes 7.5 km and its tail reaches Km 77, where traffic still arrives at 90 km/h.', confidence: 97 },
      impact: { now: 12, normal: 82, queue: 4.8, trend: 'Increasing', delay: '25–35 mins', peakQueue: 7.5, peakAt: '09:20 AM', clear: '45–60 mins', flowBack: '10:00 AM', series: 'crash' },
      actions: [A('mega', 'Activate VMS', '“Accident Ahead – Use Caution” at Km 70 and Km 78', 'Send to VMS', 1, 'warn'), A('users', 'Dispatch additional patrol unit', 'Protect the queue tail at Km 79.7', 'Dispatch', 1, 'violet'), A('ambulance', 'Coordinate ambulance and towing services', '108 ambulance and heavy tow already en route', 'Coordinate', 0, 'crit'), A('route', 'Arm the diversion; activate if queue passes 8 km', 'Via Shadnagar – Mahbubnagar road, rejoin at Km 92. Forecast peak is 7.5 km', 'Arm Plan', 0, 'good'), A('clip', 'Capture and save incident video', 'For records and insurer requests', 'Save Clip', 0, 'info')],
      responders: [{ icon: 'car', name: 'Highway Patrol Unit', eta: 4, dist: 2.1, state: 'En route' }, { icon: 'truck', name: 'Tow Truck (heavy)', eta: 6, dist: 3.5, state: 'En route' }, { icon: 'ambulance', name: 'Ambulance (108)', eta: 7, dist: 4.2, state: 'En route' }, { icon: 'shield', name: 'Traffic Police', eta: 8, dist: 4.8, state: 'Informed' }],
      timeline: [['08:32 AM', 'Incident Detected', 'done'], ['08:33 AM', 'Alert Sent to Control Room', 'done'], ['08:35 AM', 'Patrol Dispatched', 'done'], ['08:38 AM', 'Tow Truck En Route', 'now'], ['On Site', '(ETA 4 mins)', 'todo'], ['Clearance', '(Est. 45–60 mins)', 'todo'], ['Normal Flow', '(Expected by 10:00 AM)', 'todo']],
      root: { summary: 'A loaded truck braked hard for a slow vehicle joining from the Mahbubnagar link. The SUV behind was following at under one second and hit the truck; a sedan then side-swiped the SUV while swerving.', chain: [['Trigger', 'Slow merge from link road', 'Car joined at 34 km/h into an 86 km/h stream'], ['Reaction', 'Truck braked hard', 'Speed fell 78 to 22 km/h in 3.1 s'], ['Root cause', 'Unsafe following distance', 'SUV gap was 0.8 s at 84 km/h', 'root'], ['Outcome', '3-vehicle collision', 'Lanes 1 and 2 blocked', 'out']],
        factors: [['Following distance under 1 second', 'Measured from the 12 frames before impact', 72], ['Short merge taper at Km 84.3', 'Taper is 90 m; standard for this speed is 210 m', 58], ['Speed differential at merge', '52 km/h between joining car and main stream', 46], ['Morning peak density', '1,840 vehicles/hour in the SB carriageway', 24]],
        conditions: [['sun', 'Weather', 'Clear, dry surface'], ['eye', 'Visibility', 'Good, sun behind traffic'], ['road', 'Geometry', 'Straight, merge from left'], ['bulb', 'Lighting', 'Daylight'], ['gauge', 'Speed limit', '100 km/h (cars), 80 (trucks)'], ['sign', 'Signage', 'Merge warning at 150 m only']],
        prevent: ['Extend the merge taper at Km 84.3 from 90 m to 210 m.', 'Add a “Merging traffic – keep distance” VMS message during 07:30–09:30.', 'Run a following-distance enforcement drive on Km 78–86.'] } },

    { id: 'INC-2041', type: 'smoke', title: 'Vehicle Fire', sev: 'high', km: 398, dir: 'SB', near: 'Near Raptadu, Anantapur', lane: 'Shoulder, Lane 1 at risk', at: '08:39 AM', mins: 6, status: 'Fire tender requested',
      line1: 'Car on shoulder', line2: 'Open flame, thick smoke', banner: ['Open flame', 'Lane 1 at risk'], img: 'smoke.jpg', camId: 'NH-44_Km398_SB', weather: 'Clear · 29°C · Light wind from west',
      boxes: [{ x: 47, y: 17, w: 52, h: 63, label: 'Fire and smoke · 94%', tone: 'crit' }, { x: 13, y: 70, w: 46, h: 22, label: 'Vehicle · car', tone: 'warn' }],
      intelTitle: 'Fire and smoke intelligence', intel: [['car', 'Vehicle', 'Car, stopped on shoulder behind the guardrail'], ['flame', 'Visible indicators', 'Open flame and dense black smoke'], ['trend', 'Escalation trend', 'Smoke to open flame in 4 minutes'], ['road', 'Lanes affected', 'Shoulder; Lane 1 within 3 m'], ['car', 'Nearby traffic', '38 vehicles/min passing at 63 km/h'], ['users', 'Nearest fire tender', 'Anantapur station, 14 mins (11 km)']],
      ai: { detection: 'Smoke, then open flame, from a stationary car, first seen 08:39 AM.', classification: 'Vehicle fire (car)', laneImpact: 'Shoulder occupied, Lane 1 at risk', trafficImpact: 'Speed down 30% as drivers slow to look', predictive: 'Fuel tank involvement is likely within minutes. Keep traffic 50 m clear.', confidence: 94 },
      impact: { now: 63, normal: 90, queue: 0.6, trend: 'Stable', delay: '3–5 mins', peakQueue: 2.4, peakAt: '09:05 AM', clear: '40–50 mins', flowBack: '09:40 AM', series: 'mild' },
      actions: [A('flame', 'Dispatch fire tender', 'Anantapur fire station, 11 km', 'Dispatch', 1, 'crit'), A('mega', 'Activate VMS', '“Vehicle fire risk ahead – keep right” at Km 390', 'Send to VMS', 1, 'warn'), A('cone', 'Close Lane 1 for 200 m', 'Isolation zone around the car', 'Close Lane', 0, 'serious'), A('users', 'Send patrol to move the occupants clear', 'Two people seen standing near the car', 'Notify', 0, 'violet')],
      responders: [{ icon: 'flame', name: 'Fire Tender (Anantapur)', eta: 14, dist: 11, state: 'Requested' }, { icon: 'car', name: 'Highway Patrol Unit', eta: 5, dist: 3.8, state: 'En route' }, { icon: 'ambulance', name: 'Ambulance (108)', eta: 9, dist: 6.4, state: 'On standby' }],
      timeline: [['08:39 AM', 'Smoke Detected', 'done'], ['08:43 AM', 'Open Flame Detected, Severity Raised', 'done'], ['08:40 AM', 'Alert Sent to Control Room', 'done'], ['08:42 AM', 'Patrol Dispatched', 'done'], ['08:44 AM', 'Fire Tender Requested', 'now'], ['On Site', '(ETA 5 mins, patrol)', 'todo'], ['Made Safe', '(Est. 25 mins)', 'todo'], ['Recovery', '(Est. 40–50 mins)', 'todo']],
      root: { summary: 'The car slowed over 2 km before stopping, which points to an engine or electrical fault rather than a collision. It passed Marur toll plaza 9 minutes earlier with no smoke visible.', chain: [['Trigger', 'Fault while climbing', 'Km 388–396 rises 60 m'], ['Reaction', 'Speed fell to 31 km/h', 'Seen on cameras at Km 392 and 396'], ['Root cause', 'Probable engine-bay fire', 'Flame origin is forward of the cabin', 'root'], ['Outcome', 'Car burning on the shoulder', 'Fire beside a live lane', 'out']],
        factors: [['Engine bay fire origin', 'Flame starts forward of the cabin', 66], ['Progressive slow-down before stop', '78 to 31 km/h over 2 km', 52], ['Ambient temperature', '29°C and rising', 18]],
        conditions: [['sun', 'Weather', 'Clear, 29°C'], ['eye', 'Visibility', 'Good; smoke drifting east, away from lanes'], ['road', 'Geometry', 'Gentle climb, straight'], ['car', 'Vehicle class', 'Private car'], ['gauge', 'Traffic', 'Moderate, 38 veh/min'], ['toll', 'Last seen', 'Marur toll plaza, 08:30 AM']],
        prevent: ['Flag vehicles that slow steadily with hazard lights on for a patrol check before they stop.', 'Keep a fire extinguisher trolley at the Marur toll plaza, 10 km upstream.'] } },

    { id: 'INC-2039', type: 'stalled', title: 'Stalled Vehicle', sev: 'medium', km: 131.2, dir: 'SB', near: 'Near Kothakota', lane: 'Lane 2 (Centre)', at: '08:28 AM', mins: 17, status: 'Tow vehicle dispatched',
      line1: 'Lane 2 blocked', line2: 'Heavy truck', banner: ['Heavy truck', 'Lane 2 blocked'], img: 'cam-stalled-truck.jpg', camId: 'NH-44_Km131_2_SB', weather: 'Clear · 28°C',
      boxes: [{ x: 40, y: 33, w: 20, h: 44, label: 'Stalled Vehicle', tone: 'crit' }],
      intelTitle: 'Stalled vehicle intelligence', intel: [['truck', 'Vehicle type', 'Heavy vehicle (truck)'], ['mappin', 'Exact position', 'Km 131.2, Lane 2, stopped in a live lane'], ['clock', 'Stationary for', '17 minutes (since 08:28 AM)'], ['trend', 'Queue formation risk', 'Queue likely in 4–6 minutes'], ['truck', 'Nearest tow vehicle', 'Kothakota depot, 8 mins (5.6 km)'], ['gauge', 'Last observed speed', '0 km/h (since 08:28 AM)']],
      ai: { detection: 'Stationary vehicle detected for 17 minutes.', classification: 'Heavy vehicle (truck)', laneImpact: 'Lane 2 blocked', trafficImpact: 'Queue likely in 4–6 minutes. Current speed drop: −32%', predictive: 'If not cleared, delay could extend up to 15 minutes across 3–5 km.', confidence: 96 },
      impact: { now: 46, normal: 88, queue: 1.2, trend: 'Building', delay: '8–15 mins', peakQueue: 4.0, peakAt: '09:10 AM', clear: '25–35 mins', flowBack: '09:25 AM', series: 'stall' },
      actions: [A('mega', 'Activate VMS', '“Slow Down – Stalled Vehicle Ahead”', 'Send to VMS', 1, 'info'), A('truck', 'Dispatch tow vehicle', 'ETA 8 mins', 'Dispatch', 1, 'info'), A('users', 'Inform patrol team', 'Share live location and snapshot', 'Notify', 0, 'info'), A('road', 'Monitor congestion', 'Check downstream cameras', 'Track', 0, 'info'), A('file', 'Log incident', 'Auto-create maintenance ticket', 'Create Ticket', 0, 'info')],
      responders: [{ icon: 'truck', name: 'Tow Truck (Kothakota depot)', eta: 8, dist: 5.6, state: 'En route' }, { icon: 'car', name: 'Highway Patrol Unit', eta: 6, dist: 4.1, state: 'En route' }],
      timeline: [['08:28 AM', 'Vehicle Stopped', 'done'], ['08:31 AM', 'Stall Confirmed (3 min rule)', 'done'], ['08:32 AM', 'Alert Sent to Control Room', 'done'], ['08:37 AM', 'Tow Dispatched', 'now'], ['On Site', '(ETA 8 mins)', 'todo'], ['Clearance', '(Est. 25–35 mins)', 'todo']],
      root: { summary: 'The truck lost speed steadily over the previous 1.5 km with hazard lights on, then stopped in lane rather than on the shoulder. That pattern fits a mechanical failure, not a driver stop.', chain: [['Trigger', 'Loss of drive power', 'Speed fell 64 to 0 km/h over 1.5 km'], ['Reaction', 'Hazard lights on', 'Seen from Km 129.8'], ['Root cause', 'Probable mechanical breakdown', 'No collision, no tyre debris', 'root'], ['Outcome', 'Stopped in Lane 2', 'Could not cross to the 1.5 m shoulder', 'out']],
        factors: [['Gradual deceleration with hazards on', 'Consistent with drivetrain or fuel failure', 64], ['Narrow shoulder at Km 131', '1.5 m; truck could not pull fully clear', 48], ['Vehicle age class', 'Registration series suggests 12+ years', 22]],
        conditions: [['sun', 'Weather', 'Clear, dry'], ['eye', 'Visibility', 'Good, 600 m sight line'], ['road', 'Geometry', 'Straight, level'], ['barrier', 'Shoulder', '1.5 m paved, narrow'], ['gauge', 'Traffic', 'Moderate, 1,260 veh/hour'], ['truck', 'Vehicle', 'Heavy goods truck, loaded']],
        prevent: ['Widen the shoulder at Km 130–132 during the next resurfacing cycle.', 'Add a breakdown lay-by sign pointing to the Km 133 bay.'] } },

    { id: 'INC-2038', type: 'flooding', title: 'Flooding / Waterlogging', sev: 'high', km: 441, dir: 'Both', near: 'Near Penukonda underpass', lane: '1 lane each side', at: '08:21 AM', mins: 24, status: 'Pump crew en route',
      line1: '1 lane affected', line2: 'Water accumulation', banner: ['Water depth ~22 cm', 'Rising'], img: 'flooding.jpg', camId: 'NH-44_Km441_SB', hotspot: 'HS-03', weather: 'Heavy rain · 31 mm/h · 24°C',
      boxes: [{ x: 3, y: 40, w: 92, h: 50, label: 'Standing water · est. 22 cm', tone: 'info' }, { x: 5, y: 2, w: 76, h: 44, label: '', tone: '' }],
      intelTitle: 'Flooding intelligence', intel: [['mappin', 'Location', 'Km 440.6 – 441.3, underpass approach'], ['road', 'Affected lanes', 'Lane 1 both directions'], ['ruler', 'Estimated extent', '700 m long, ~22 cm deep at kerb'], ['gauge', 'Traffic speed', '28 km/h (normal 86)'], ['trend', 'Progression', 'Depth +6 cm in 20 minutes, rain continuing'], ['route', 'Recommendation', 'Close Lane 1; divert light vehicles if depth passes 30 cm']],
      ai: { detection: 'Standing water detected across Lane 1, surface reflection and wheel spray changed at 08:21 AM.', classification: 'Waterlogging, moderate (est. 22 cm)', laneImpact: 'Lane 1 unusable in both directions', trafficImpact: 'Speed down 67%, queue 2.1 km SB', predictive: 'At the current rain rate the depth passes 30 cm by 09:15 AM, unsafe for cars and two-wheelers.', confidence: 91 },
      impact: { now: 28, normal: 86, queue: 2.1, trend: 'Increasing', delay: '12–20 mins', peakQueue: 5.5, peakAt: '09:30 AM', clear: 'Depends on rainfall', flowBack: '11:00 AM', series: 'crash' },
      actions: [A('cone', 'Close Lane 1 both directions', 'Km 440.6 to 441.3', 'Close Lane', 1, 'serious'), A('wrench', 'Dispatch pump crew', 'Penukonda maintenance unit, 12 mins', 'Dispatch', 1, 'info'), A('mega', 'Activate VMS', '“Waterlogging ahead – slow down” at Km 430 and Km 452', 'Send to VMS', 0, 'warn'), A('route', 'Prepare light-vehicle diversion', 'Via Penukonda town road, +9 mins', 'Activate Plan', 0, 'good')],
      responders: [{ icon: 'wrench', name: 'Pump Crew (Penukonda)', eta: 12, dist: 9.2, state: 'En route' }, { icon: 'car', name: 'Highway Patrol Unit', eta: 3, dist: 1.6, state: 'On site' }, { icon: 'shield', name: 'Traffic Police', eta: 15, dist: 10.4, state: 'Informed' }],
      timeline: [['08:21 AM', 'Water Detected', 'done'], ['08:22 AM', 'Alert Sent to Control Room', 'done'], ['08:26 AM', 'Patrol On Site', 'done'], ['08:34 AM', 'Pump Crew Dispatched', 'now'], ['Lane Closure', '(Pending approval)', 'todo'], ['Pumping', '(Est. 60–90 mins)', 'todo'], ['Normal Flow', '(Expected by 11:00 AM)', 'todo']],
      root: { summary: 'Rain has been above 25 mm/h for 50 minutes. The side drain on the underpass approach is not carrying water away, and this is the sixth waterlogging event at this spot in 90 days.', chain: [['Trigger', 'Heavy rain for 50 minutes', '31 mm/h now, 38 mm so far'], ['Reaction', 'Run-off collects at the sag point', 'Lowest point of the underpass approach'], ['Root cause', 'Blocked side drain', 'Flagged twice this season, not yet desilted', 'root'], ['Outcome', 'Lane 1 waterlogged', '22 cm and rising', 'out']],
        factors: [['Side drain blockage', 'Open maintenance ticket MT-5127 since 02 Sep', 74], ['Rainfall intensity above 25 mm/h', 'Threshold seen in all 6 past events', 61], ['Sag-curve geometry', 'Water has no natural outfall', 40]],
        conditions: [['rain', 'Weather', 'Heavy rain, 31 mm/h'], ['eye', 'Visibility', 'Reduced, ~350 m'], ['road', 'Geometry', 'Sag curve into underpass'], ['wrench', 'Drainage', 'Side drain blocked (MT-5127)'], ['gauge', 'Traffic', 'Moderate, mixed with two-wheelers'], ['clock', 'History', '6 events in 90 days']],
        prevent: ['Desilt the side drain (ticket MT-5127) before the next rain band.', 'Install a pump sump and a water-level sensor at Km 441.', 'Pre-position a pump crew when rainfall forecast passes 25 mm/h.'] } },

    { id: 'INC-2037', type: 'queue', title: 'Slow Traffic · Toll Plaza Queue', sev: 'medium', km: 58, dir: 'SB', near: 'Raikal Toll Plaza', lane: 'FASTag Lanes 3 &amp; 4', at: '08:20 AM', mins: 25, status: 'Monitoring', go: 'toll/queue',
      line1: '~12 min delay', line2: 'Lane 3 queue above 10 minutes', banner: ['Queue 0.9 km', '~12 min delay'], img: 'cam-toll-plaza.jpg', camId: 'NH-44_Km58_Plaza', weather: 'Clear · 28°C',
      boxes: [{ x: 34, y: 52, w: 16, h: 30, label: '12 min · 18 vehicles', tone: 'crit' }, { x: 52, y: 52, w: 16, h: 30, label: '10 min · 15 vehicles', tone: 'crit' }],
      intelTitle: 'Queue intelligence', intel: [['toll', 'Plaza', 'Raikal, 6 lanes SB (4 FASTag, 2 cash)'], ['clock', 'Longest wait', 'Lane 3, 12 minutes, 18 vehicles'], ['truck', 'Vehicle mix', 'Trucks 32% (normal 20%)'], ['gauge', 'Processing rate', '5.1 veh/min per lane (normal 7.4)'], ['trend', 'Predicted wait', '15 minutes by 09:10 AM'], ['check', 'Recommendation', 'Switch Cash Lane 5 to FASTag']],
      ai: { detection: 'Queue length in Lanes 3 and 4 above the 10-minute threshold.', classification: 'Toll plaza congestion', laneImpact: 'Lanes 3 and 4 overloaded, Lane 5 under-used', trafficImpact: 'Average wait 6.5 minutes, tailback 0.9 km', predictive: 'Tailback reaches 1.6 km by 09:10 AM unless a lane is re-allocated.', confidence: 93 },
      impact: { now: 42, normal: 70, queue: 0.9, trend: 'Building', delay: '10–12 mins', peakQueue: 1.6, peakAt: '09:10 AM', clear: '30 mins after lane switch', flowBack: '09:30 AM', series: 'stall' },
      actions: [A('toll', 'Open the plaza queue view', 'Lane-by-lane queues and wait times', 'Open', 1, 'info'), A('refresh', 'Switch Cash Lane 5 to FASTag', 'Cuts Lane 3 and 4 wait by ~4 minutes', 'Switch Lane', 1, 'good'), A('mega', 'Activate VMS', '“Use Lanes 1, 2 and 5” at Km 56', 'Send to VMS', 0, 'warn')],
      responders: [{ icon: 'user', name: 'Plaza Supervisor', eta: 0, dist: 0, state: 'On site' }, { icon: 'users', name: 'Lane Marshals (2)', eta: 2, dist: 0.1, state: 'Deployed' }],
      timeline: [['08:20 AM', 'Queue Threshold Crossed', 'done'], ['08:28 AM', 'Consider Additional FASTag Lane', 'done'], ['08:38 AM', 'Lane 4 Queue Building', 'done'], ['08:40 AM', 'Lane 3 Above 10 Minutes', 'now'], ['Lane Switch', '(Awaiting supervisor)', 'todo'], ['Normal Flow', '(Expected by 09:30 AM)', 'todo']],
      root: { summary: 'Truck share is 32% against a normal 20% because freight held at the Shadnagar lay-by overnight was released together at 08:00. Trucks take about twice as long per transaction, and two cash lanes are nearly idle.', chain: [['Trigger', 'Freight released together', 'Shadnagar lay-by cleared at 08:00'], ['Reaction', 'Truck share rose to 32%', 'Normal is 20%'], ['Root cause', 'Lane allocation did not follow demand', '78% FASTag traffic on 4 of 6 lanes', 'root'], ['Outcome', 'Lanes 3 and 4 over 10 minutes', 'Tailback 0.9 km', 'out']],
        factors: [['Lane allocation mismatch', '78% FASTag usage, 67% of lanes', 68], ['High truck share', '32% vs 20% normal', 55], ['Slow reader in Lane 3', 'Read retries up 3x since 07:50', 31]],
        conditions: [['sun', 'Weather', 'Clear'], ['toll', 'Lanes open', '6 of 6'], ['tag', 'FASTag usage', '78%'], ['truck', 'Truck share', '32%'], ['gauge', 'Arrivals', '1,842 vehicles in 30 mins'], ['wrench', 'Equipment', 'Lane 3 reader degraded']],
        prevent: ['Make Lane 5 a dynamic lane that follows the FASTag share.', 'Stagger freight release from the Shadnagar lay-by.', 'Replace the Lane 3 tag reader.'] } },

    { id: 'INC-2036', type: 'hgv', title: 'Stranded Heavy Vehicle', sev: 'medium', km: 296, dir: 'SB', near: 'Gooty ghat section', lane: 'Lane 1 and shoulder', at: '08:05 AM', mins: 40, status: 'Crane requested',
      line1: 'Multi-axle trailer on gradient', line2: 'Needs heavy recovery crane', banner: ['Multi-axle trailer', 'Lane 1 blocked on climb'], img: 'truck-queue.jpg', camId: 'NH-44_Km296_SB', hotspot: 'HS-02', weather: 'Clear · 30°C',
      boxes: [{ x: 21, y: 18, w: 38, h: 76, label: 'Stranded HGV · 40 min', tone: 'warn' }],
      intelTitle: 'Heavy vehicle recovery intelligence', intel: [['truck', 'Vehicle', 'Multi-axle trailer, 40 ft container'], ['mappin', 'Location', 'Km 296, 4.2% climb'], ['box', 'Load context', 'Loaded container, est. 38 tonnes'], ['road', 'Obstruction', 'Lane 1 and shoulder'], ['wrench', 'Recovery complexity', 'High: standard tow cannot pull on this gradient'], ['truck', 'Right resource', '50-tonne crane, Gooty yard, 22 mins']],
      ai: { detection: 'Heavy vehicle stationary on a gradient for 40 minutes.', classification: 'Stranded multi-axle trailer', laneImpact: 'Lane 1 and shoulder blocked', trafficImpact: 'Speed down 51%, trucks queuing behind on the climb', predictive: 'Truck queue reaches 3 km by 09:30 AM; following trucks also risk stalling on the climb.', confidence: 92 },
      impact: { now: 41, normal: 84, queue: 1.8, trend: 'Increasing', delay: '10–18 mins', peakQueue: 3.0, peakAt: '09:30 AM', clear: '70–90 mins', flowBack: '10:15 AM', series: 'stall' },
      actions: [A('truck', 'Dispatch 50-tonne recovery crane', 'Gooty yard, 22 mins', 'Dispatch', 1, 'serious'), A('mega', 'Activate VMS', '“Heavy vehicles keep right – stranded truck ahead”', 'Send to VMS', 1, 'warn'), A('users', 'Post a patrol at the foot of the climb', 'Hold following trailers at Km 293 lay-by', 'Notify', 0, 'violet')],
      responders: [{ icon: 'truck', name: 'Recovery Crane (50 t)', eta: 22, dist: 14, state: 'Requested' }, { icon: 'car', name: 'Highway Patrol Unit', eta: 0, dist: 0, state: 'On site' }],
      timeline: [['08:05 AM', 'Vehicle Stopped on Climb', 'done'], ['08:08 AM', 'Alert Sent to Control Room', 'done'], ['08:19 AM', 'Patrol On Site', 'done'], ['08:31 AM', 'Standard Tow Failed', 'done'], ['08:36 AM', 'Crane Requested', 'now'], ['Recovery', '(Est. 70–90 mins)', 'todo']],
      root: { summary: 'The trailer slowed to walking pace on the 4.2% climb and stopped. This is the eleventh breakdown on this 4 km gradient in 90 days, mostly loaded multi-axle vehicles on hot mornings.', chain: [['Trigger', 'Sustained 4.2% climb', '3.8 km long'], ['Reaction', 'Speed fell to 9 km/h', 'Then stopped at Km 296'], ['Root cause', 'Overheating under heavy load', 'Pattern matches 8 of 11 past cases', 'root'], ['Outcome', 'Lane 1 blocked on gradient', 'Standard tow could not recover it', 'out']],
        factors: [['Heavy load on long gradient', 'Est. 38 tonnes on a 3.8 km climb', 70], ['No crawler lane or lay-by', 'Nowhere to stop clear of traffic', 52], ['Recovery resource mismatch', 'First tow sent was too light; 27 minutes lost', 44]],
        conditions: [['sun', 'Weather', 'Clear, 30°C'], ['road', 'Geometry', '4.2% climb, gentle curve'], ['barrier', 'Shoulder', '2 m paved'], ['truck', 'Vehicle', 'Multi-axle trailer, loaded'], ['gauge', 'Traffic', 'Freight heavy, 41% trucks'], ['clock', 'History', '11 breakdowns in 90 days']],
        prevent: ['Build a crawler lane lay-by at Km 295.', 'Station a heavy recovery crane at Gooty during 07:00–11:00.', 'Send the crane first for any multi-axle stall on Km 294–298.'] } },

    { id: 'INC-2035', type: 'roadworks', title: 'Roadworks · Lane Closure', sev: 'medium', km: 268, dir: 'SB', near: 'Near Dhone', lane: 'Lane 1 closed for 1.2 km', at: '07:55 AM', mins: 50, status: 'Planned work active',
      line1: 'Lane closure', line2: 'Scheduled maintenance', banner: ['Scheduled maintenance', 'Lane 1 closed'], img: 'roadworks.jpg', camId: 'NH-44_Km268_SB', weather: 'Clear · 29°C',
      boxes: [{ x: 1, y: 52, w: 58, h: 44, label: 'Work zone · Lane 1 closed', tone: 'warn' }, { x: 61, y: 37, w: 19, h: 44, label: 'Entering at 71 km/h · limit 40', tone: 'crit' }],
      intelTitle: 'Work-zone intelligence', intel: [['cone', 'Work-zone boundaries', 'Km 267.4 – 268.6, Lane 1'], ['road', 'Active lanes', '1 of 2 open'], ['users', 'Worker and vehicle movement', '9 workers, 2 plant vehicles'], ['gauge', 'Traffic speed through zone', '44 km/h (posted 40)'], ['alert', 'Unsafe behaviour', '14 vehicles above 70 km/h in the last hour'], ['trend', 'Queue formation', '0.8 km, stable']],
      ai: { detection: 'Planned lane closure active; vehicles are entering the zone well above the 40 km/h limit.', classification: 'Work-zone risk, moderate', laneImpact: 'Lane 1 closed for 1.2 km', trafficImpact: 'Speed down 49%, queue 0.8 km', predictive: 'Queue stays under 1.5 km unless the truck share rises after 10:00 AM.', confidence: 89 },
      impact: { now: 44, normal: 86, queue: 0.8, trend: 'Stable', delay: '8–10 mins', peakQueue: 1.5, peakAt: '10:30 AM', clear: 'Work ends 04:00 PM', flowBack: '04:30 PM', series: 'mild' },
      actions: [A('users', 'Alert the site supervisor', 'Fast entries past the taper; ask for a flagman at Km 267.2', 'Notify', 1, 'crit'), A('mega', 'Activate VMS', '“Roadworks – 40 km/h” at Km 262', 'Send to VMS', 0, 'warn'), A('shield', 'Request speed enforcement', '14 vehicles above 70 km/h in the zone', 'Request', 0, 'violet')],
      responders: [{ icon: 'user', name: 'Site Supervisor', eta: 0, dist: 0, state: 'On site' }, { icon: 'car', name: 'Highway Patrol Unit', eta: 11, dist: 8.2, state: 'Available' }],
      timeline: [['07:30 AM', 'Closure Set Up', 'done'], ['07:55 AM', 'Closure Detected and Matched to Permit', 'done'], ['08:36 AM', 'Entry Speed Alert: 71 km/h in Zone', 'now'], ['Supervisor Alert', '(Pending)', 'todo'], ['Work Ends', '(04:00 PM)', 'todo']],
      root: { summary: 'This is planned resurfacing under permit RW-0916. The risk is not the closure itself but drivers entering the zone too fast, with nine workers a lane-width away.', chain: [['Trigger', 'Planned resurfacing', 'Permit RW-0916, 07:30 AM – 04:00 PM'], ['Reaction', 'Lane 1 closed for 1.2 km', 'Taper starts Km 267.2'], ['Root cause', 'Late speed reduction by drivers', 'First warning sign only 300 m before taper', 'root'], ['Outcome', 'Work-zone safety risk', '14 entries above 70 km/h in an hour', 'out']],
        factors: [['Advance warning too short', '300 m; should be 1 km at 100 km/h', 63], ['No speed enforcement in zone', 'Average entry speed 58 km/h', 47], ['Cone spacing wide at taper', 'Gap of 18 m seen', 29]],
        conditions: [['sun', 'Weather', 'Clear'], ['cone', 'Permit', 'RW-0916, valid'], ['road', 'Geometry', 'Straight, level'], ['sign', 'Signage', 'First sign 300 m before taper'], ['gauge', 'Traffic', '980 veh/hour'], ['users', 'Workforce', '9 workers on site']],
        prevent: ['Move the first warning sign to 1 km before the taper.', 'Add a portable VMS and a speed display at Km 266.', 'Brief the crew on staying inside the cone line.'] } },

    { id: 'INC-2034', type: 'debris', title: 'Debris on Road · Fallen Load', sev: 'low', km: 176.3, dir: 'SB', near: 'Between Pebbair and Kurnool', lane: 'Lane 2 (Right)', at: '07:48 AM', mins: 57, status: 'Maintenance crew assigned',
      line1: 'Right lane', line2: 'Branches and fronds across the lane', banner: ['Fallen load: branches', 'Right lane'], img: 'debris.jpg', camId: 'NH-44_Km176_3_SB', weather: 'Clear · 28°C',
      boxes: [{ x: 8, y: 44, w: 56, h: 24, label: 'Debris · fallen load · 88%', tone: 'warn' }],
      intelTitle: 'Debris intelligence', intel: [['octagon', 'Object detected', 'Fallen load: branches and palm fronds'], ['ruler', 'Size', 'Spread over ~6 m, up to 0.4 m high'], ['road', 'Affected lane', 'Lane 2 (right, fast lane)'], ['gauge', 'Approach speeds', 'Average 96 km/h'], ['alert', 'Collision exposure', '11 swerves in the last 30 minutes'], ['wrench', 'Nearest maintenance crew', 'Pebbair unit, 16 mins (19 km)']],
      ai: { detection: 'Static object in Lane 2 since 07:48 AM; vehicles swerving around it.', classification: 'Fallen load (vegetation)', laneImpact: 'Lane 2 partly obstructed', trafficImpact: 'Speed down 26%; no queue', predictive: 'Swerve rate rises with traffic after 09:00 AM; side-swipe risk goes up.', confidence: 88 },
      impact: { now: 68, normal: 92, queue: 0, trend: 'None', delay: '1–2 mins', peakQueue: 0.4, peakAt: '09:15 AM', clear: '20 mins once crew arrives', flowBack: '09:25 AM', series: 'mild' },
      actions: [A('wrench', 'Dispatch maintenance crew', 'Pebbair unit, 16 mins', 'Dispatch', 1, 'info'), A('mega', 'Activate VMS', '“Debris in right lane – keep left” at Km 170', 'Send to VMS', 0, 'warn'), A('users', 'Ask patrol to clear if passing', 'Patrol P-07 is 9 km upstream', 'Notify', 0, 'violet')],
      responders: [{ icon: 'wrench', name: 'Maintenance Crew (Pebbair)', eta: 16, dist: 19, state: 'Assigned' }, { icon: 'car', name: 'Highway Patrol P-07', eta: 7, dist: 9, state: 'Available' }],
      timeline: [['07:48 AM', 'Object Detected', 'done'], ['07:51 AM', 'Classified as Fallen Load', 'done'], ['07:52 AM', 'Alert Sent to Control Room', 'done'], ['08:30 AM', 'Crew Assigned', 'now'], ['Clearance', '(Est. 20 mins on arrival)', 'todo']],
      root: { summary: 'A tractor-trailer carrying cut branches and palm fronds lost part of its load at Km 176. The same trailer was seen at Km 152 with the load stacked above its side boards and no cover.', chain: [['Trigger', 'Overloaded, uncovered trailer', 'Seen at Km 152 camera'], ['Reaction', 'Load shifted at speed', 'Km 176.3, 07:47 AM'], ['Root cause', 'Unsecured load', 'No tarpaulin or tie-downs', 'root'], ['Outcome', 'Debris in the fast lane', '11 swerves so far', 'out']],
        factors: [['Unsecured load on a farm trailer', 'Load stacked above the side boards, uncovered', 71], ['Slow assignment', '38 minutes from alert to crew assignment', 49], ['High approach speed', '96 km/h average in Lane 2', 33]],
        conditions: [['sun', 'Weather', 'Clear, surface 41°C'], ['eye', 'Visibility', 'Good'], ['road', 'Geometry', 'Straight'], ['gauge', 'Traffic', 'Light, fast'], ['truck', 'Source vehicle', 'Tractor-trailer, seen Km 152'], ['clock', 'Exposure', '57 minutes so far']],
        prevent: ['Auto-assign debris alerts in the fast lane to the nearest patrol within 5 minutes.', 'Flag uncovered or over-height loads at toll plazas before they reach the open road.'] } },

    { id: 'INC-2033', type: 'wrongway', title: 'Wrong-Way Vehicle', sev: 'high', km: 9.6, dir: 'SB carriageway, moving NB', near: 'Shamshabad ORR service link', lane: 'Lane 1, against traffic', at: '07:40 AM', mins: 65, closedAt: '07:49 AM', status: 'Intercepted · under review',
      line1: 'Service Road (ORR Link)', line2: 'Moving towards Hyderabad', banner: ['Against traffic for 1.4 km', 'Intercepted 07:49 AM'], img: 'wrongway.jpg', camId: 'NH-44_Km9_6_SB', hotspot: 'HS-04', weather: 'Clear · 26°C',
      boxes: [{ x: 40, y: 17, w: 8, h: 10, label: 'Wrong-Way Vehicle · 46 km/h', tone: 'crit' }], path: [[44, 28], [40, 52], [33, 84]],
      intelTitle: 'Wrong-way intelligence', intel: [['mappin', 'Position when detected', 'Km 9.6, Lane 1 of the SB carriageway'], ['arrowl', 'Direction', 'Northbound, against traffic'], ['gauge', 'Speed', '46 km/h'], ['route', 'Trajectory', 'Entered via the exit ramp at Km 10.9, travelled 1.4 km'], ['car', 'Vehicles at risk', '23 oncoming vehicles passed within 1 lane'], ['alert', 'Estimated conflict point', 'Km 9.1, crest with 180 m sight distance']],
      ai: { detection: 'Vehicle moving against the flow direction on the SB carriageway.', classification: 'Wrong-way light vehicle (car)', laneImpact: 'Lane 1, oncoming', trafficImpact: '23 oncoming vehicles exposed over 9 minutes', predictive: 'Head-on conflict was likely at the Km 9.1 crest within 40 seconds of the first alert.', confidence: 98 },
      impact: { now: 64, normal: 78, queue: 0, trend: 'Cleared', delay: 'None now', peakQueue: 0.5, peakAt: '07:46 AM', clear: 'Cleared 07:49 AM', flowBack: '07:55 AM', series: 'mild' },
      actions: [A('file', 'Send evidence pack to Traffic Police', 'Clip, plate read and trajectory', 'Send', 1, 'violet'), A('wrench', 'Raise ticket for ramp treatment', 'Tyre-killer strip and signage at Km 10.9 exit ramp', 'Create Ticket', 1, 'info'), A('clip', 'Save incident video', '9 minutes across 3 cameras', 'Save Clip', 0, 'info')],
      responders: [{ icon: 'car', name: 'Highway Patrol P-02', eta: 0, dist: 0, state: 'Intercepted at 07:49' }, { icon: 'shield', name: 'Traffic Police', eta: 0, dist: 0, state: 'Case opened' }],
      timeline: [['07:40 AM', 'Wrong-Way Movement Detected', 'done'], ['07:40 AM', 'Alert and VMS “Wrong-Way Vehicle Ahead”', 'done'], ['07:42 AM', 'Patrol P-02 Dispatched', 'done'], ['07:49 AM', 'Vehicle Intercepted at Km 8.2', 'done'], ['08:10 AM', 'Evidence Pack Compiled', 'now'], ['Case Closure', '(With Traffic Police)', 'todo']],
      root: { summary: 'The driver missed the Shamshabad exit and turned back along the exit ramp rather than drive 6 km to the next U-turn. This is the fifth wrong-way entry from the same ramp in 90 days.', chain: [['Trigger', 'Missed exit at Km 10.9', 'Next legal U-turn is 6 km away'], ['Reaction', 'Driver reversed up the exit ramp', 'Seen on ramp camera 07:39 AM'], ['Root cause', 'Ramp has no physical wrong-way deterrent', 'No tyre-killer, faded “No Entry” marking', 'root'], ['Outcome', '1.4 km against traffic', '23 vehicles exposed', 'out']],
        factors: [['No wrong-way deterrent on the ramp', '5 entries from this ramp in 90 days', 76], ['Long detour after a missed exit', '6 km to the next U-turn', 58], ['Exit signage too late', 'Final sign 200 m before the ramp', 35]],
        conditions: [['sun', 'Weather', 'Clear'], ['eye', 'Visibility', 'Good; crest at Km 9.1 limits sight to 180 m'], ['road', 'Geometry', 'Exit ramp, single lane'], ['sign', 'Signage', '“No Entry” marking faded'], ['gauge', 'Traffic', 'Morning peak, 2,100 veh/hour'], ['clock', 'History', '5 entries in 90 days']],
        prevent: ['Install a tyre-killer strip and “Wrong Way” signs on the Km 10.9 exit ramp.', 'Open the median U-turn at Km 12 to cut the detour from 6 km to 1 km.', 'Add an advance exit sign at 1 km.'] } },

    { id: 'INC-2032', type: 'animal', title: 'Animal on Highway', sev: 'medium', km: 322, dir: 'SB', near: 'Near Gooty', lane: 'Lane 1 (Left)', at: '07:18 AM', mins: 87, status: 'Patrol on site',
      line1: 'Left lane', line2: 'Cattle on carriageway', banner: ['Cattle on carriageway', 'Herd of 10 or more'], img: 'animal.jpg', camId: 'NH-44_Km322_SB', hotspot: 'HS-05', weather: 'Clear · 28°C',
      boxes: [{ x: 17, y: 34, w: 42, h: 56, label: 'Cattle · 95%', tone: 'warn' }, { x: 58, y: 24, w: 36, h: 26, label: 'Herd · 8+', tone: 'warn' }],
      intelTitle: 'Animal intrusion intelligence', intel: [['paw', 'Classification', 'Cattle, herd of 10 or more'], ['mappin', 'Location', 'Km 322, Lane 1 and median'], ['arrow', 'Movement', 'Slowly crossing west to east'], ['road', 'Affected lanes', 'Lane 1; Lane 2 intermittently'], ['gauge', 'Approaching traffic', '88 km/h average, 22 veh/min'], ['alert', 'Collision risk', 'Medium; 6 hard-braking events']],
      ai: { detection: 'Large animals on the carriageway since 07:18 AM.', classification: 'Cattle (herd of 10 or more)', laneImpact: 'Lane 1 blocked at times', trafficImpact: 'Speed down 25%, 6 hard-braking events', predictive: 'Herd usually clears within 2 hours; risk stays until the median fence gap is closed.', confidence: 95 },
      impact: { now: 66, normal: 88, queue: 0.3, trend: 'Stable', delay: '2–4 mins', peakQueue: 0.8, peakAt: '08:00 AM', clear: 'Patrol moving herd now', flowBack: '09:00 AM', series: 'mild' },
      actions: [A('mega', 'Keep VMS warning active', '“Animals on road – slow down” at Km 316', 'Extend VMS', 1, 'warn'), A('wrench', 'Escalate the overdue fence repair', 'Ticket MT-5093, open 36 days: 340 m of median fence at Km 321.8', 'Escalate', 1, 'info'), A('users', 'Inform the village panchayat', 'Herd owner contact via Gooty mandal office', 'Notify', 0, 'violet')],
      responders: [{ icon: 'car', name: 'Highway Patrol P-11', eta: 0, dist: 0, state: 'On site' }],
      timeline: [['07:18 AM', 'Animals Detected', 'done'], ['07:19 AM', 'VMS Warning Activated', 'done'], ['07:24 AM', 'Patrol Dispatched', 'done'], ['07:41 AM', 'Patrol On Site', 'now'], ['Carriageway Clear', '(Est. 09:00 AM)', 'todo']],
      root: { summary: 'Cattle from the grazing land west of the highway cross each morning through a broken stretch of median fence. Eight intrusions in 90 days have come through the same gap.', chain: [['Trigger', 'Morning grazing movement', '06:30 – 08:00 AM daily'], ['Reaction', 'Herd crosses at the fence gap', 'Km 321.8'], ['Root cause', 'Broken median fence, 340 m', 'Reported 11 Aug, not repaired', 'root'], ['Outcome', 'Cattle on carriageway', '6 hard-braking events', 'out']],
        factors: [['Broken median fence', '340 m gap at Km 321.8', 80], ['No cattle crossing nearby', 'Nearest underpass is 4 km away', 45], ['Repair backlog', 'Ticket MT-5093 open for 36 days', 38]],
        conditions: [['sun', 'Weather', 'Clear'], ['eye', 'Visibility', 'Good'], ['barrier', 'Fencing', '340 m broken'], ['road', 'Geometry', 'Straight, level'], ['gauge', 'Traffic', 'Light, fast'], ['clock', 'History', '8 intrusions in 90 days']],
        prevent: ['Repair the 340 m of median fence at Km 321.8.', 'Schedule a patrol pass at 06:30 AM on this stretch.', 'Study a cattle underpass at Km 322.'] } },

    { id: 'INC-2031', type: 'pedestrian', title: 'Pedestrian on Highway', sev: 'medium', km: 512.6, dir: 'NB', near: 'Near Chikkaballapur', lane: 'Right shoulder', at: '06:52 AM', mins: 113, status: 'Monitoring · recurring',
      line1: 'Right shoulder', line2: 'Person walking along carriageway', banner: ['Person on carriageway', 'Recurring location'], img: 'pedestrian.jpg', camId: 'NH-44_Km512_6_NB', weather: 'Clear · 23°C',
      boxes: [{ x: 79, y: 42, w: 11, h: 44, label: 'Pedestrian · 92%', tone: 'warn' }],
      intelTitle: 'Pedestrian intelligence', intel: [['walk', 'Pedestrian location', 'Km 512.6, right shoulder, NB'], ['arrow', 'Direction', 'Walking north, with traffic'], ['clock', 'Time on carriageway', '9 minutes in the first event; 14 people since 06:52'], ['car', 'Nearest approaching vehicles', '3 within 200 m at 91 km/h'], ['alert', 'Estimated conflict zone', 'Km 512.4 – 512.9, bus stop to village path'], ['users', 'Patrol intervention', 'P-16 passed at 07:10 AM']],
      ai: { detection: 'Person walking on the shoulder and crossing the carriageway.', classification: 'Pedestrian; 14 separate people since 06:52 AM', laneImpact: 'Shoulder; carriageway crossed 5 times', trafficImpact: 'No speed change; 2 hard-braking events', predictive: 'Crossings peak again at 05:00 – 06:30 PM when the return bus stops.', confidence: 92 },
      impact: { now: 88, normal: 89, queue: 0, trend: 'None', delay: 'None', peakQueue: 0, peakAt: '—', clear: 'Not applicable', flowBack: '—', series: 'flat' },
      actions: [A('mega', 'Activate VMS', '“Pedestrians ahead – slow down” at Km 518', 'Send to VMS', 1, 'warn'), A('users', 'Schedule patrol presence', '06:45 – 07:30 AM and 05:00 – 06:30 PM', 'Schedule', 0, 'violet'), A('file', 'Raise a safety audit request', 'Foot overbridge or at-grade crossing study', 'Create Ticket', 0, 'info')],
      responders: [{ icon: 'car', name: 'Highway Patrol P-16', eta: 12, dist: 9.5, state: 'Available' }],
      timeline: [['06:52 AM', 'Pedestrian Detected', 'done'], ['06:53 AM', 'Alert Sent to Control Room', 'done'], ['07:10 AM', 'Patrol Pass', 'done'], ['08:30 AM', '14th Person Logged', 'now'], ['Safety Audit', '(Proposed)', 'todo']],
      root: { summary: 'An informal bus stop on the northbound side sits opposite a village path. People get off the bus and cross the highway on foot because the nearest foot overbridge is 1.8 km away.', chain: [['Trigger', 'Informal bus stop at Km 512.6', 'Buses stop on the shoulder'], ['Reaction', 'Passengers walk along and across', '14 people this morning'], ['Root cause', 'No safe crossing near the village path', 'Nearest overbridge 1.8 km away', 'root'], ['Outcome', 'Pedestrians on a 100 km/h road', '2 hard-braking events', 'out']],
        factors: [['No crossing facility', 'Overbridge is 1.8 km north', 74], ['Informal bus stop', 'Not in the approved stop list', 60], ['Gap in the side barrier', '6 m opening at the village path', 42]],
        conditions: [['sun', 'Weather', 'Clear, 23°C'], ['eye', 'Visibility', 'Good'], ['road', 'Geometry', 'Straight'], ['barrier', 'Side barrier', '6 m gap'], ['gauge', 'Traffic', '89 km/h average'], ['clock', 'History', 'Daily, morning and evening']],
        prevent: ['Move the bus stop to the Km 514 bus bay with a foot overbridge.', 'Close the 6 m barrier gap once the stop has moved.', 'Interim: patrol presence at peak crossing times.'] } },

    { id: 'INC-2030', type: 'visibility', title: 'Low Visibility · Fog', sev: 'low', km: 540, dir: 'Both', near: 'Devanahalli – Airport stretch', lane: 'All lanes', at: '06:30 AM', mins: 135, status: 'Easing',
      line1: 'Km 530 – 548', line2: 'Visibility ~300 m, improving', banner: ['Visibility ~300 m', 'Improving'], img: 'fog.jpg', camId: 'NH-44_Km540_SB', weather: 'Fog lifting · 21°C',
      boxes: [],
      intelTitle: 'Low visibility intelligence', intel: [['mappin', 'Affected section', 'Km 530 – 548 (18 km)'], ['eye', 'Estimated visibility', '~300 m now (120 m at 06:45 AM)'], ['gauge', 'Vehicle speeds', '62 km/h average, spread 35–95'], ['car', 'Traffic density', 'High, airport traffic'], ['clock', 'Incident history', '3 fog collisions here last winter'], ['trend', 'Risk progression', 'Falling; clear expected by 09:15 AM']],
      ai: { detection: 'Image contrast loss across 6 cameras since 06:30 AM.', classification: 'Fog, moderate, easing', laneImpact: 'All lanes, both directions', trafficImpact: 'Speed down 30%; wide speed spread raises rear-end risk', predictive: 'Visibility back above 500 m by 09:15 AM.', confidence: 90 },
      impact: { now: 62, normal: 89, queue: 0, trend: 'Easing', delay: '4–6 mins', peakQueue: 0, peakAt: '—', clear: '09:15 AM', flowBack: '09:30 AM', series: 'mild' },
      actions: [A('mega', 'Keep VMS speed advisory', '“Fog – 60 km/h” on 4 signs', 'Extend VMS', 1, 'warn'), A('bulb', 'Keep highway lighting on', 'Km 530 – 548 until 09:30 AM', 'Extend', 0, 'info')],
      responders: [{ icon: 'car', name: 'Highway Patrol P-18', eta: 0, dist: 0, state: 'Patrolling section' }],
      timeline: [['06:30 AM', 'Low Visibility Detected', 'done'], ['06:32 AM', 'VMS Speed Advisory On', 'done'], ['06:45 AM', 'Visibility at Minimum (120 m)', 'done'], ['08:30 AM', 'Visibility 300 m, Improving', 'now'], ['Clear', '(Expected 09:15 AM)', 'todo']],
      root: { summary: 'Radiation fog formed over the low ground near the Devanahalli lakes after a clear, still night. It is seasonal and expected; the risk is the wide spread of vehicle speeds inside it.', chain: [['Trigger', 'Clear, still night near lakes', 'Humidity 96% at 05:30 AM'], ['Reaction', 'Fog over 18 km', 'Minimum visibility 120 m'], ['Root cause', 'Wide speed spread in fog', '35 to 95 km/h in the same lane', 'root'], ['Outcome', 'Raised rear-end risk', 'No collisions today', 'out']],
        factors: [['Speed variance in fog', 'Spread of 60 km/h between vehicles', 62], ['Dense airport traffic', '2,300 veh/hour from 06:00 AM', 44], ['No fog-activated lighting', 'Lights are on a timer, off at 06:15 AM', 30]],
        conditions: [['fog', 'Weather', 'Fog, easing'], ['eye', 'Visibility', '~300 m'], ['road', 'Geometry', 'Straight, 6 lanes'], ['bulb', 'Lighting', 'Timer based'], ['gauge', 'Traffic', 'High'], ['clock', 'History', '3 fog collisions last winter']],
        prevent: ['Link highway lighting to the visibility sensors, not a timer.', 'Add variable speed limit signs on Km 530 – 548.'] } },
  ];
  D.incident = id => D.incidents.find(i => i.id === id);
  D.sevTone = { high: 'crit', medium: 'warn', low: 'good' };
  D.incPin = (i, o) => { o = o || {}; const t = D.types[i.type]; return { type: 'incident', km: i.km, icon: t.icon, tone: i.sev === 'high' ? 'crit' : i.sev === 'medium' ? (t.tone === 'violet' ? 'violet' : 'serious') : 'warn', go: `incident/${i.id}`, tip: `<b>${i.title}</b><br>${D.kmLabel(i.km)} · ${i.near}<br>${i.line1} · ${i.at}`, sel: o.sel === i.id, callout: o.callout === i.id ? { title: t.label, lines: [`${D.kmLabel(i.km)} (${i.dir})`, i.line1], tone: o.calloutTone || 'crit', icon: 'alert', iconTone: 'crit' } : null }; };

  /* ---------- cameras (key cameras shown on maps and in Live View; the corridor has 1,248) ---------- */
  D.cameras = [
    { id: 'CAM-0096', km: 9.6, img: 'wrongway.jpg', status: 'ok', inc: 'INC-2033' }, { id: 'CAM-0310', km: 31, img: 'cam-corridor-2.jpg', status: 'ok' }, { id: 'CAM-0580', km: 58, img: 'cam-toll-plaza.jpg', status: 'ok', label: 'Raikal Toll Plaza', inc: 'INC-2037' },
    { id: 'CAM-0845', km: 84.5, img: 'cam-accident.jpg', status: 'ok', inc: 'INC-2040' }, { id: 'CAM-1010', km: 101, img: 'cam-corridor-3.jpg', status: 'off' }, { id: 'CAM-1312', km: 131.2, img: 'cam-stalled-truck.jpg', status: 'ok', inc: 'INC-2039' },
    { id: 'CAM-1520', km: 152, img: 'cam-corridor-1.jpg', status: 'ok' }, { id: 'CAM-1763', km: 176.3, img: 'debris.jpg', status: 'ok', inc: 'INC-2034' }, { id: 'CAM-2120', km: 212, img: 'cam-corridor-4.jpg', status: 'ok' },
    { id: 'CAM-2680', km: 268, img: 'roadworks.jpg', status: 'ok', inc: 'INC-2035' }, { id: 'CAM-2960', km: 296, img: 'truck-queue.jpg', status: 'ok', inc: 'INC-2036' }, { id: 'CAM-3220', km: 322, img: 'animal.jpg', status: 'ok', inc: 'INC-2032' },
    { id: 'CAM-3600', km: 360, img: 'cam-corridor-2.jpg', status: 'warn' }, { id: 'CAM-3980', km: 398, img: 'smoke.jpg', status: 'ok', inc: 'INC-2041' }, { id: 'CAM-4410', km: 441, img: 'flooding.jpg', status: 'ok', inc: 'INC-2038' },
    { id: 'CAM-4720', km: 472, img: 'toll-booth.jpg', status: 'ok', label: 'Bagepalli Toll Plaza' }, { id: 'CAM-5126', km: 512.6, img: 'pedestrian.jpg', status: 'ok', inc: 'INC-2031' }, { id: 'CAM-5400', km: 540, img: 'fog.jpg', status: 'ok', inc: 'INC-2030' },
  ];
  D.camPin = c => ({ type: 'camera', km: c.km, icon: c.status === 'off' ? 'videooff' : 'video', tone: c.status === 'off' ? 'crit' : c.status === 'warn' ? 'warn' : 'navy', go: c.inc ? `incident/${c.inc}` : 'live/grid', tip: `<b>${c.id}</b> · ${D.kmLabel(c.km)}<br>${c.label || D.nearest(c.km)} · ${c.status === 'off' ? 'Offline since 08:32 AM' : c.status === 'warn' ? 'Image quality degraded' : 'Live'}` });

  /* ---------- toll plazas. rev = today so far (₹ lakh), leak24 = estimated leakage last 24 h (₹ lakh) ---------- */
  D.plazas = [
    { id: 'raikal', name: 'Raikal', km: 58, rev: 28.4, leak24: 2.3, wait: 6.5, fastag: 78, veh: 1842, status: 'Queue building' }, { id: 'shakapur', name: 'Shakapur', km: 115, rev: 14.2, leak24: 0.9, wait: 2.1, fastag: 81, veh: 960, status: 'Normal' },
    { id: 'pullur', name: 'Pullur', km: 200, rev: 16.8, leak24: 5.8, wait: 2.8, fastag: 74, veh: 1104, status: 'Leakage anomaly' }, { id: 'amakathadu', name: 'Amakathadu', km: 252, rev: 11.6, leak24: 0.8, wait: 1.9, fastag: 80, veh: 782, status: 'Normal' },
    { id: 'kasepalli', name: 'Kasepalli', km: 318, rev: 10.9, leak24: 0.7, wait: 1.7, fastag: 79, veh: 731, status: 'Normal' }, { id: 'marur', name: 'Marur', km: 388, rev: 12.7, leak24: 1.3, wait: 2.4, fastag: 82, veh: 866, status: 'Normal' },
    { id: 'bagepalli', name: 'Bagepalli', km: 472, rev: 13.5, leak24: 1.1, wait: 3.2, fastag: 84, veh: 905, status: 'Normal' }, { id: 'devanahalli', name: 'Devanahalli', km: 545, rev: 19.9, leak24: 1.7, wait: 4.1, fastag: 88, veh: 1390, status: 'Normal' },
  ]; /* rev sums to 128.0 lakh = ₹1.28 Cr; leak24 sums to 14.6 lakh against ₹3.42 Cr collected in 24 h (4.3%) */
  D.toll = { revToday: 1.28, rev24: 3.42, leak24: 14.6, leakPct: 4.3, leakMonth: 4.1, flagged24: 312, confirmedPct: 71 };
  D.plazaPin = p => ({ type: 'toll', km: p.km, icon: 'toll', tone: p.status === 'Normal' ? 'info' : p.id === 'pullur' ? 'violet' : 'warn', below: 1, go: p.id === 'raikal' ? 'toll/queue' : p.id === 'pullur' ? 'toll/leakage' : 'toll/overview', tip: `<b>${p.name} Toll Plaza</b> · Km ${p.km}<br>₹ ${p.rev} lakh today · wait ${p.wait} mins<br>${p.status}` });

  /* ---------- assets (totals match the Assets & Maintenance mockup) ---------- */
  D.assets = { total: 2412, healthy: 1978, attention: 264, fault: 120, maintenance: 50,
    classes: [{ key: 'cameras', label: 'Cameras', icon: 'video', count: 1248, pct: 98, word: 'operational', tone: 'good' }, { key: 'vms', label: 'VMS Signs', icon: 'sign', count: 216, pct: 94, word: 'operational', tone: 'good' }, { key: 'power', label: 'Power &amp; IT Assets', icon: 'zap', count: 142, pct: 96, word: 'operational', tone: 'good' }, { key: 'road', label: 'Road Assets', icon: 'road', count: 486, pct: 91, word: 'healthy', tone: 'warn' }, { key: 'sensors', label: 'Sensors', icon: 'wifi', count: 320, pct: 88, word: 'operational', tone: 'warn' }] };

  /* global search: incidents, cameras, plazas, places */
  VQ.searchExtra = [() => [
    ...D.incidents.map(i => ({ icon: D.types[i.type].icon, label: `${i.id} · ${i.title}`, more: `${D.kmLabel(i.km)} · ${i.near}`, kind: 'Incident', go: `incident/${i.id}` })),
    ...D.cameras.map(c => ({ icon: 'video', label: c.id, more: `${D.kmLabel(c.km)} · ${c.label || D.nearest(c.km)}`, kind: 'Camera', go: c.inc ? `incident/${c.inc}` : 'live/grid' })),
    ...D.plazas.map(p => ({ icon: 'toll', label: `${p.name} Toll Plaza`, more: `Km ${p.km}`, kind: 'Toll plaza', go: p.id === 'raikal' ? 'toll/queue' : 'toll/overview' })),
    ...D.hotspots.map(h => ({ icon: 'crosshair', label: h.name, more: `${h.kind} · Km ${h.from}–${h.to}`, kind: 'Hotspot', go: 'incidents/hotspots' })),
  ]];
  return D;
})();
